### ISSUE TITLE
Please rename to something less generic

### ISSUE THREAD

**Issue by unixorn** [ch4rli3kop/my-custom-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by ch4rli3kop** [comment]
Thanks very much for your interest in my project.
I renamed project. https://github.com/ch4rli3kop/ch4rli3.zsh-theme
Thanks! Have a nice day!

2021년 3월 2일 (화) 오전 11:43, Joe Block <notifications@github.com>님이 작성:
